version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clinic-db
    environment:
      - POSTGRES_DB=clinic_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3fc7c6434c596014
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: clinic-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clinic_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=3fc7c6434c596014
    networks:
      - clinic-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

networks:
  clinic-network:
    driver: bridge

volumes:
  postgres-data: